estimator: FasterRCNN
backbone: resnet50
num_classes: 91
task: object_detection
train:
  epochs: 26
  batch_size: 4
  accumulation_steps: 8
  log_frequency: 1000
  dataset:
    name: CocoDetection
    args:
      version: 2017
      split: train
val:
  batch_size: 4
  dataset:
    name: CocoDetection
    args:
      version: 2017
      split: val
test:
  batch_size: 4
  dataset:
    name: CocoDetection
    args:
      version: 2017
      split: val
metrics:
  mAP:
    name: MeanAveragePrecision
  mAP50IOU:
    name: MeanAveragePrecision50IOU
  mAR:
    name: MeanAverageRecall
  AP50IOU:
    name: AveragePrecision50IOU
optimizer:
  name: Adam
  args:
    lr: 2.0e-4
pretrained: False
pretrained_backbone: True
synchronize_metrics: True
