estimator: FasterRCNN
backbone: resnet50
num_classes: 65
task: object_detection
train:
  epochs: 50
  batch_size: 8
  accumulation_steps: 8
  log_frequency: 30
  dataset:
    name: GoogleGroceriesReal
    args:
      split: train
val:
  batch_size: 8
  dataset:
    name: GoogleGroceriesReal
    args:
      split: test
test:
  batch_size: 8
  dataset:
    name: GoogleGroceriesReal
    args:
      split: test
metrics:
  mAP:
    name: MeanAveragePrecision
  mAP50IOU:
    name: MeanAveragePrecision50IOU
  mAR:
    name: MeanAverageRecall
  AP50IOU:
    name: AveragePrecision50IOU
optimizer:
  name: Adam
  args:
    lr: 2.0e-4
pretrained: False
pretrained_backbone: True
synchronize_metrics: True
checkpoint_file: None
